### PR TITLE
added portfolio

### PR DESCRIPTION
**Pull request by code-soham**

### CODE REVIEW

**Review by Priyadarshan2000 — CHANGES_REQUESTED** [review]
@code-soham rename index.html file name

**Comment by code-soham** [comment]
@Priyadarshan2000 sorry I dont follow, what should I rename it as? :)

**Comment by Priyadarshan2000** [comment]
> 

Projectname.html

**Comment by code-soham** [comment]
@Priyadarshan2000 updated, kindly review

**Review by Priyadarshan2000 — APPROVED** [review]

**Comment by Priyadarshan2000** [comment]
> @Priyadarshan2000 updated, kindly review

ya merge done

**Pull request merged**
